site_name: My Journal
site_url: https://myjournal.github.io
site_description: My Journal
repo_url: https://github.com/myjournal/myjournal.github.io

extra_css:
  - custom.css

remote_branch: master

theme: readthedocs # quotes look odd... - fixed in custom.css

nav:
  - Home: index.md
  - Childhood:
    - The Watch: childhood/1983-the-watch.md
  - Teen:
    - The 98-pound weakling: teen/1994-the-98lb-weakling.md
    - The hospital: teen/1995-the-hospital.md
  - College:
    - Coca-Cola: cocacola.md
  -Adult
